// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpC7dPz0VAQU4AE3sp88_jjB8TfYICCu0',
    appId: '1:587144620346:web:791e9ca4d78a70dce1c803',
    messagingSenderId: '587144620346',
    projectId: 'proyecte-pm',
    authDomain: 'proyecte-pm.firebaseapp.com',
    storageBucket: 'proyecte-pm.firebasestorage.app',
    measurementId: 'G-LV0C0WJ439',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCndgONmGnwQYJl4qt57uImCpI2Y6BzUVs',
    appId: '1:587144620346:android:76da7b8d3969dfeee1c803',
    messagingSenderId: '587144620346',
    projectId: 'proyecte-pm',
    storageBucket: 'proyecte-pm.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpC7dPz0VAQU4AE3sp88_jjB8TfYICCu0',
    appId: '1:587144620346:web:da3c7ba65c46fecee1c803',
    messagingSenderId: '587144620346',
    projectId: 'proyecte-pm',
    authDomain: 'proyecte-pm.firebaseapp.com',
    storageBucket: 'proyecte-pm.firebasestorage.app',
    measurementId: 'G-40ZL8V0V2H',
  );

}