// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGmwQ-41EBeAct7UPKj20YUvIfyDiS6k0',
    appId: '1:440325395288:web:7f4bfb25688109717a8b2d',
    messagingSenderId: '440325395288',
    projectId: 'spotyupc',
    authDomain: 'spotyupc.firebaseapp.com',
    storageBucket: 'spotyupc.firebasestorage.app',
    measurementId: 'G-BCH81B3431',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvG6fEa9ZCI5RZhErVjCbyBTNi3NlgoA',
    appId: '1:440325395288:android:977a4466dd375d467a8b2d',
    messagingSenderId: '440325395288',
    projectId: 'spotyupc',
    storageBucket: 'spotyupc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGmwQ-41EBeAct7UPKj20YUvIfyDiS6k0',
    appId: '1:440325395288:web:43d61d7e0db544c97a8b2d',
    messagingSenderId: '440325395288',
    projectId: 'spotyupc',
    authDomain: 'spotyupc.firebaseapp.com',
    storageBucket: 'spotyupc.firebasestorage.app',
    measurementId: 'G-769R53XH0J',
  );
}
